name: release.yml
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release
        required: true

jobs:
  empower-plant-release:
    name: Release Build of EmpowerPlant
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Setup Sentry CLI
        uses: mathieu-bour/setup-sentry-cli@v1.3.0
        with:
          version: 3.3.5
          token: ${{ secrets.SENTRY_AUTH_TOKEN }}
      - name: Run Deploy Script
        run: ./deploy_project.sh ${{ github.event.inputs.version }} ${{ secrets.SENTRY_ORG }} ${{ secrets.SENTRY_PROJECT }} ${{ secrets.SENTRY_AUTH_TOKEN }}
        shell: sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload to Sentry Size Analysis
        run: |
          xcodebuild archive \
            -project EmpowerPlant.xcodeproj \
            -scheme EmpowerPlant \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath build/EmpowerPlant.xcarchive \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            -quiet
          sentry-cli build upload build/EmpowerPlant.xcarchive \
            --org ${{ secrets.SENTRY_ORG }} \
            --project ${{ secrets.SENTRY_PROJECT }} \
            --build-configuration Release \
            --head-sha ${{ github.sha }} \
            --head-ref "${{ github.ref_name }}"
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
