name: test.yml

on:
  pull_request:

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and Test
      run: xcodebuild -project EmpowerPlant.xcodeproj -scheme EmpowerPlant -configuration Debug -derivedDataPath build -destination "platform=iOS Simulator,OS=latest,name=iPhone 15" -quiet test

    - name: Generate Coverage Report
      run: |
        xcrun xccov view --report build/Logs/Test/*.xccovreport > coverage.txt
