## Test
name: test.yml

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Slather
      run: gem install slather

    - name: Build and Test
      run: make test
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: 214d9137-2c5a-4eaf-9327-c6031f13795a
        fail_ci_if_error: true
        verbose: true
