name: test.yml

on:
  pull_request:

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Slather
      run: gem install slather

    - name: Build and Test
      run: xcodebuild -project EmpowerPlant.xcodeproj -scheme EmpowerPlant -configuration Debug -derivedDataPath build -destination "platform=iOS Simulator,OS=latest,name=iPhone 15" -quiet test | slather coverage --configuration Debug && exit ${PIPESTATUS[0]}
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
