name: test.yml

on:
  pull_request:

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Slather
      run: gem install slather

    - name: Build and Test
      run: make test
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
